### ISSUE TITLE
Genbil - test from nbitx template generated incorrectly

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#499] opened 2019-07-08 08:21 UTC
Hi All,

After the update to 1.20 version of Genbi the nbitx template stopped to work for me.

It generates only half of the test (system-under-test part) into the nbits file.

Example (nbitx template used):
```xml
<test name="TC01 test">
  <description>TC01 test.</description>
  <category>TC01</category>
  <system-under-test>
    <execution>
      <query connectionString="@tst" timeout-milliSeconds="10000"><![CDATA[
      SELECT 1
      ]]></query>
    </execution>
  </system-under-test>
  <assert>
    <equalTo>
      <column index="0" role="key" type="numeric" />
      <query connectionString="@tst" timeout-milliSeconds="10000"><![CDATA[
      SELECT 1
      ]]></query>
    </equalTo>
  </assert>
</test>
```

Result (nbits file - version 1.20):
```xml
<?xml version="1.0" encoding="utf-8"?>
<testSuite xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://NBi/TestSuite">
  <settings />
  <test name="TC01 test">
    <description>TC01 test.</description>
    <category>TC01</category>
    <system-under-test>
      <execution>
        <query timeout-milliSeconds="10000"><![CDATA[
      SELECT 1
      ]]></query>
      </execution>
    </system-under-test>
  </test>
</testSuite>
```

Result (nbits file - version 1.19):
```xml
<?xml version="1.0" encoding="utf-8"?>
<testSuite xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://NBi/TestSuite">
  <settings />
  <test name="TC01 test">
    <description>TC01 test.</description>
    <category>TC01</category>
    <system-under-test>
      <execution>
        <query connectionString="@tst" timeout-milliSeconds="10000"><![CDATA[
      SELECT 1
      ]]></query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="key" type="numeric" />
        <query connectionString="@tst" timeout-milliSeconds="10000"><![CDATA[
      SELECT 1
      ]]></query>
      </equalTo>
    </assert>
  </test>
</testSuite>
```

NOTE:
I have also noticed that the connection string in the query tag is missing, too.

Could you check it please?

Cheers.

**Comment by Seddryck** [comment] 2019-07-08 11:22
Just tried the proposed template and it's working fine (assert is correctly generated and connection-string references are there). Are you sure it's 1.20 and not 1.21-beta?

By the way, I tested with the latest 1.21-beta and it's also working fine. I'm also concerned because the xml element settings is not serailized as it should with version 1.20 or 1.21 ... I'm expecting:

``` xml
<testSuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://NBi/TestSuite">
  <settings>
    <default apply-to="system-under-test" />
    <default apply-to="assert" />
    <default apply-to="setup-cleanup" />
    <default apply-to="everywhere" />
  </settings>
  <test name="Test 01">
    <description>Test 01.</description>
    <category>TC01</category>
    <system-under-test>
      <execution>
        <query connection-string="@tst" timeout-milliSeconds="10000"><![CDATA[
      SELECT 1
      ]]></query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="key" type="numeric" />
        <query connection-string="@tst" timeout-milliSeconds="10000"><![CDATA[
      SELECT 1
      ]]></query>
      </equalTo>
    </assert>
  </test>
</testSuite>
```

**Comment by fefeslon** [comment] 2019-07-08 12:49
I have downloaded the zips from github and appveyor (1.20).

None of them works for me.

At first I have just rewritten the old Genbi content, now I have tried to delete and then copy the 1.20 version.

Tried to generate some tests from nbitt template and it works (nbitx is still incomplete).

Do you have any kind of help/advice for me?

**NOTE:** I am using the external settings (.nbiset) in the project.

Cheers.

**Comment by Seddryck** [comment] 2019-07-08 14:42
Try with exactly these files (files are expected to be at the root of the NBi installation folder)  from bellow or from this [archive](https://github.com/Seddryck/NBi/files/3368905/ExecutionEqualTo.zip) and give me the result:

ExecutionEqualTo.nbitt
```xml
<test name="$name$">
  <description>$name$.</description>
  <category>TC01</category>
  <system-under-test>
    <execution>
      <query connectionString="@$refConn$" timeout-milliSeconds="10000">
        <![CDATA[
      $query$
      ]]>
      </query>
    </execution>
  </system-under-test>
  <assert>
    <equalTo>
      <column index="0" role="key" type="numeric" />
      <query connectionString="@$refConn$" timeout-milliSeconds="10000">
        <![CDATA[
      $query$
      ]]>
      </query>
    </equalTo>
  </assert>
</test>
```

ExecutionEqualTo.genbil
```
case load file 'ExecutionEqualTo.csv';

template load file 'ExecutionEqualTo.nbitt';
suite generate;
suite save as 'ExecutionEqualTo.nbits';
```

ExecutionEqualTo.csv
```
name;query;refConn
Test 01;SELECT 1;tst
```

And execute following command ...
```
genbi.exe 'ExecutionEqualTo.genbil'
```

On my side, I clearly have no problem of serialization:

```xml
<?xml version="1.0" encoding="utf-8"?>
<testSuite xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://NBi/TestSuite">
  <settings>
    <default apply-to="system-under-test" />
    <default apply-to="assert" />
    <default apply-to="setup-cleanup" />
    <default apply-to="everywhere" />
  </settings>
  <test name="Test 01">
    <description>Test 01.</description>
    <category>TC01</category>
    <system-under-test>
      <execution>
        <query connection-string="@tst" timeout-milliSeconds="10000"><![CDATA[
      SELECT 1
      ]]></query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="key" type="numeric" />
        <query connection-string="@tst" timeout-milliSeconds="10000"><![CDATA[
      SELECT 1
      ]]></query>
      </equalTo>
    </assert>
  </test>
</testSuite>
```

If you have not this exact result ... I'd be really surprised and I'd recommend that your try to install NBi on another folder and check that you have not registered some of the dlls to the GAC. Now if you get the same result that I received, the issue is clearly not in the template.

**Comment by fefeslon** [comment] 2019-07-09 07:05
Hey Cedric,

As I have written above, the **nbitt template works** fine for me (sorry if it had confused you).

What does not work is the nbitx template.

If some more details will help you to investigate, just let me know.

The first comment (above) contains the nbitx template used (you can see the result there, too).

I am using external settings in the project (.nbiset file).

Genbil file:
```
suite include file 'test_template.nbitx';

suite save as 'tests.nbits';
```

Nbits file is generated without any error message.

**Comment by Seddryck** [comment] 2019-07-10 22:28
Ok, I get it. I can reproduce. As a work-around, I'd definitively recommend to switch to the 2.X notation and use the ```equal-to``` assertion in place of ```equalTo``` (and by the way change from ```execution\query``` to ```result-set\query```). 

I didn't check if it was complex to fix this bug but I won't spend a lot of time to fix a bug related to the notation 1.X ... Moving to the notation 2.X is really he way to go.

**Comment by Seddryck** [comment] 2019-07-14 13:20
I checked this issue and this is definitively something on purpose. Old notations such as ```equivalentTo```, ```subsetOf```, ```fasterThan```, ```syntacticallyCorrect```, ```equalTo``` are not accepted anymore by genbiL. The best advise is to switch to the new notation with ```equal-to```, ```subset-of``` ...

**Closed as completed by Seddryck** 2019-07-14 13:20 UTC
Labels: bug, work-around

**Comment by fefeslon** [comment] 2019-07-15 11:28
Ok, this solved my issue.

Is there any documentation regarding this?

I see the notations mixed on the http://www.nbi.io (e.g. Documentation/Equivalence of two result-sets uses the old one and the link to the syntax 2.0 does not work at all.)

Anyway thanks for the help!

Cheers.

**Comment by Seddryck** [comment] 2019-07-15 14:31
http://www.nbi.io/docs/syntax-2-0/ refers to a an [issue](https://github.com/Seddryck/NBi/issues/288) where I try to manage the current status. I'll try to update the documentation to reflect the syntax 2.0
