### ISSUE TITLE
Use Nbi in Visual Studio without the bootstrapper

### ISSUE THREAD

**Issue by eetawil** [Seddryck/NBi#319] opened 2017-11-03 17:52 UTC
Hello,
First of all, thanks for building NBi.

I'm a QA and I'm using TFS/VS tools for test automation.

1. I want to run my test using `Microsoft.VisualStudio.TestTools.UnitTesting` and not from the NUnit provided, is there a way for that?

2. Is there a way (maybe using NBi.Framework.Tools or NBi.Framework directly) to be able to use the assertion engine of NBi? Or maybe have access to the assertion aspect of NBi so that I can link it to the Microsoft.VisualStudio.TestTools.UnitTesting Assertion?
` example: Assert.IsTrue(Nbi.Assert(Dataset1, Dataset2));`

**Comment by Seddryck** [comment] 2017-11-04 13:09
That's a complex set of questions to answer because I don't know your background and the root cause of your questions.

If I take your example as a starting point: what will happen when the test is failing? Because you're encapsulating the assertion performed by NBi in an ```Assert.IsTrue```, your end-result will be something like ```expecting 'true' but was 'false'``` You'll be losing a large part of the added-value of NBi because you won't receive the complete message detailing which rows are in error. IMHO, not an option (and pragmatically NBi.Assert doesn't exist).

The only public API that I'm supporting is the XML one (NBi.Xml) and the runtime (NBi.NUnit.Runtime). It means that it's not really sustainable to try to directly connect to NBi.Core or NBi.NUnit because I change them at each release (and I'm currently refactoring a lot on these areas). I wouldn't recommend to do it. If you go to the details, you'll see that the constraint ```equalTo``` is not comparing two datasets but two resultSetServices (I'm preparing the 2.x release and definitively want to go on this direction). Meaning that even if you wanted to directly use this constraint, you'd have to encapsulate all your datasets in resultSetServices. That's possible but again I'm not supporting the class ```ResultSetService``` as a public API (we could discuss this to change it).

Your remaining option, is to code in C# by creating the different Xml objects and also to write a kind of NBi.Microsoft ... re-implementing each constraint. That's a huge work and the specification of your test will be clumsy! IMHO, not an option. If you really want to go this route, contact me before you start because I'm changing a lot of things to be prepared for the 2.X syntax.

So back to the roots: why do you've a requirement such as using ```Microsoft.VisualStudio.TestTools.UnitTesting```. Is it because of the UI (The title of your question, let me think about it)? Is it because it's NUnit 2.6 and not 3.x? Other? Could you share your concerns? Have you tried to use NBi as intended? What was not ideal according to you?

**Comment by eetawil** [comment] 2017-11-06 12:54
Thank you for your response, ill give you more details about what our goal is. I'm not sure if you're familiar with TFS but TFS provided a test management tool. In that tool, we can create test cases and link them in [Test Method] in VS. 

Then we can launch the test cases directly from that tool and have all the results sent back in an attachment with a Pass/Fail status. We could use the Nbi framework to achieve this inside a [Test Method] (autogenerate the XML on the fly and the via cmdline execute the tests) but I'm not sure how to report back the result in that case. Is there a way to get back the results in an Object?

**Comment by FuegoArtificial** [comment] 2017-11-06 18:21
@eetawil as far as I know, NUnit (which NBi extends) generates xml files as result files. When execution the cmd line you can provide the path and in the next step read the same file and parse it as you prefer, returning the results.
Do I understand your question correctly?

**Comment by eetawil** [comment] 2017-11-06 18:31
@FuegoArtificial Yes I guess that could work, I could Map that XML results file into an object and work with it. I wanted to know if it would have been possible to get the object directly without having to do such thing.
If that's the only way then I think I could work with that.
Thanks

**Comment by Seddryck** [comment] 2017-11-06 19:50
@eetawil I never gave a try to Microsoft Test Management, so I won't be really helpful on this. 

About the result of tests, I'd go in the same direction that @FuegoArtificial has discussed.

About the mapping of test methods to a test defined in MTM, it's more complex. NBi has exactly one method identified with a ```[TestMethod]``` attribute. If your goal is to be able to play exactly one test from MTM, I'd guess it will be really difficult.

**Comment by FuegoArtificial** [comment] 2017-11-06 20:35
@eetawil I could also imagine that NUnit has an accessible object model. That could help. If you find a solution for that I'd be interested to hear about the basic approach!

The current approach with NBi is usually to test instances of BI-solutions, no (nightly?) builds within TFS (yet?).

**Comment by Seddryck** [comment] 2017-11-06 21:29
> The current approach with NBi is usually to test instances of BI-solutions, no (nightly?) builds within TFS (yet?).

Huuum, I and some other people are using it with TeamCity to run tests just after the build and deployment :-)

**Comment by Seddryck** [comment] 2017-12-05 00:06
Closing that , doesn't seem needed to maintain it opened.

**Closed as completed by Seddryck** 2017-12-05 00:06 UTC
Labels: question

**Comment by Kapilhitup** [comment] 2018-01-12 09:08
There is no demonstration and Video available about the functionality of this product. Please let me know if it is available.
