### ISSUE TITLE
setup using store proc

### ISSUE THREAD

**Issue by shiv-2019** [Seddryck/NBi#639] opened 2021-02-13 13:12 UTC
hi,

Is it possible to use connection string in Set up and execute Store proc which loads the test table in DB.
``` xml
  </settings>
  <!--define your tests here under-->
  <test name="My first test">
  <setup>
  <tasks>
    <sql-run connectionString ="Server=DQlDB;Database=IntegrationTests;Trusted_Connection=True;">
      EXEC [TestData].[MarketSetup] 
    </sql-run>
  </tasks>
</setup>
    <system-under-test>
      <execution>
        <query>select 'ok'</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="key" type="text"/>
        <query>
          SELECT 'ok'
        </query>
      </equalTo>
    </assert>
  </test>
</testSuite>
```

**Comment by Seddryck** [comment] 2021-02-13 16:07
Sounds like a duplicate of #327

**Closed as completed by Seddryck** 2021-02-13 16:07 UTC
Labels: duplicate
