### ISSUE TITLE
Subsets/supersets for test results

### ISSUE THREAD

**Issue by BenCurvers** [Seddryck/NBi#274] opened 2017-05-03 06:35 UTC
Hello,

Please consider the following scenario: a queryresult X needs to be tested against a result of query Y (assert). In some cases it is expected that X or Y contains more rows. A as result the test will fail stating that unexpected rows were found.

It would be convenient in some cases to indicate that the assert result set will contain more rows (or the other way arround) so that the testoutput turns green.

Best Regards,
Ben C.

**Comment by Seddryck** [comment] 2017-05-03 07:22
Hi Ben,

This is indeed a valid scenario and I'll consider this for the next release. In addition of ```equalTo``` NBi will support ```subsetOf``` and ```contains```. These assertions will work exactly such as ```equalTo``` (with support of tolerance, intervals, ...) but will respectively not report missing rows and unexepected rows.

**Comment by Seddryck** [comment] 2017-08-16 22:08
Duplicate of #196

**Closed as completed by Seddryck** 2017-08-16 22:08 UTC
Labels: duplicate, feature-request

**Comment by Seddryck** [comment] 2017-09-02 13:04
It's available in a preview of release 1.16: https://ci.appveyor.com/project/Seddryck/nbi/build/1.16.0-ci.1
