### ISSUE TITLE
ETL tests don't run if you've not installed SSIS 2014 on the machine executing the tests

### ISSUE THREAD

**Issue by Mric78** [Seddryck/NBi#97] opened 2015-07-28 12:15 UTC
Hello,
I would like to know if there is a minimum version to run NBI with SSIS.
I'm on SSIS 2008 R2 and here I have the error below :

NBi.NUnit.Runtime.TestSuite.The package is faster than 10 seconds:
System.IO.FileLoadException : Could not load file or assembly 'Microsoft.SqlServer.ManagedDTS, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).

There is a configuration error or just because it's 2008 !

Thanks in advance

**Comment by Seddryck** [comment] 2015-07-28 13:00
NBi's builds are tested with a SQL Server 2012 (But SQL Server 2014 is also installed on thismachine). The main development machine is running a SQL Server 2014. These two versions are safe. Most of the time, I don't perform any test on 2008R2 or previous versions.

The problem that you've is clearly related to 2008R2. The dll of microsoft for SQL Server are a nightmare but I'll try to check this issue during the week-end.

**Comment by Seddryck** [comment] 2015-07-28 13:04
Could you post your test? I will also check that its definition is correct for a SQL Server 2008R2

**Comment by Seddryck** [comment] 2015-07-28 17:56
Oups, sorry don't know why I've closed this issue.

Well, indeed, it doesn't work with SSIS 2008R2 or 2012 (except if you've installed on the same machine SSIS 2014). I'll fix this in the next release.

**Comment by FuegoArtificial** [comment] 2015-07-29 16:41
Hello Seddryck,

a similar issue occurs with genbi not executing queries to catch test cases and being in an 2012-environment. Maybe it's related? The Error message is:

Source: NBi.Core
Type: System.IO.FileNotFoundException
Description:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.

Cheers,
Tilo

**Comment by Seddryck** [comment] 2015-07-29 17:18
for the issue with Genbi, just copy paste the dll Microsoft.analysisServices.adomdClient that you have in your "framework" folder into the Genbi folder. It will solve your problem.

**Comment by Seddryck** [comment] 2015-08-01 22:01
I've decided to treat this as a "feature-request" and not a bug. NBi has never supported to use ETL on something else than SSIS 2014. It means that I'll change something on the etl definition to select the correct version of Sql Server.

I've started to implement a solution to use 2012 and 2014 (already available on appVeyor). Will continue to use 2008R2 (and stop there ... don't have any hope for 2008 or 2005).

**Comment by Seddryck** [comment] 2015-08-02 00:09
@Mric78 (and @FuegoArtificial) I've compiled a new version of NBi resolving this issue about SSIS 2008R2, 2012 and 2014 ... at least I hope. It's a pain for me to test it (because I don't have any server with just 2008R2 or just 2012) so your feedback is vital!

The version is available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.11.0.99015 (download from artefacts/framework). 

You've to adapt your test and add the attribute `version="SqlServer2008R2"` (or `version="SqlServer2012"`) to your `etl`element to enforce NBi to use the correct dlls. (By default/if not specified 2014 will be used)

``` xml
<etl version="SqlServer2008R2" server="." folder="..."/>
```

Keep in mind that the test must run on the machine with the ETL (no remote testing currently supported). Also 2008R2 doesn't support the `Catalog` option

**Comment by Mric78** [comment] 2015-08-02 06:58
Thanks, unfortunatly i'm not available to test it until 2 weeks but be sure I will test it on my return. Thanks again for your support and reactivity

**Comment by FuegoArtificial** [comment] 2015-08-04 12:41
Hi @Seddryck,
I won't have feedback on ETL-Tests soon. We currently don't have the focus on tests of ETL packages due to conducting the tests after deployment already. Permanent data integration (before/after ETL) and (data) availability-tests are important from my point of view.
It might be slightly off topic: Do you have a common scenario in mind where testing of ETL-packages with nbi would come in handy? :) If it's no topic for this thread perhaps we can exchange opinions via pm/mail :)

**Comment by Seddryck** [comment] 2015-08-04 13:48
No problem, I'll wait the feedback of @Mric78 

We setup a source with interesting data for the etl (data valid, datya on an alternative path, data to discard, data creating an exception), then we run an etl and finally we perform a query on the tables to be sure the etl has correctly handled the data.

Another way is to insert lot of data into a table, then run the ETL and check the performance of this ETL (Less than 20 seconds ...)

Perhaps @Mric78 is creating other kind of tests, don't know.

**Comment by Mric78** [comment] 2015-08-13 10:12
Hi,
sorry for the delay, I made my tests this morning and all seems great.
I'm able to execute a simple package (execute query and generate file) with 2008R2.

Exemple of my test configuration :
`<etl version="SqlServer2008R2" path="D:\ETL\" name="CreateODS.dtsx">
<parameter name="ApplicationCode">MyApp</parameter>
</etl>`

If you need me to test something else, I'm available for it.
Thanks for your time and for this new feature :)

**Comment by Seddryck** [comment] 2015-08-13 12:55
Ok cool, it's a good news ... finally understand something about SSIS dlls' hell. I'll merge this to master and it will be part of the release 1.11 in a few weeks. In the mean time you can continue to the use preview version.

**Closed as completed** 2015-08-13 18:08 UTC
Labels: feature-request, preview-available
