### ISSUE TITLE
Don't take into default parameters

### ISSUE THREAD

**Issue by bipedro** [Seddryck/NBi#163] opened 2016-02-17 17:23 UTC
Hi,

I'm using settings/default to create global parameters to use through the whole test-suite for the system-under-test and assert tags (check code example below).

This is the test-suite xml which is failing:

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<testSuite name="testsuitename" xmlns="http://NBi/TestSuite">
    <settings>
        <default apply-to="system-under-test">
            <connectionString>Provider=MDX connection string</connectionString>
            <parameter name="DaysToGoBackMDX" >
            30
            </parameter>
        </default>
        <default apply-to="assert">
            <connectionString>sql connection string</connectionString>
            <parameter name="DaysToGoBackSQL" sql-type="int">
            30
            </parameter>
        </default>
    </settings>
    <test name="MDX R1 vs MDX 2 Value">
        <system-under-test>
            <execution>
                <query>
                    MDX code
                </query>
            </execution>
        </system-under-test>
        <assert>
            <equalTo> <column  index="0" role="value" type="numeric"  />
                <query connectionString=mdx connection string>
                    mdx code
                </query>
            </equalTo>
        </assert>
    </test>
</testSuite>
```

I have solved this by adding this piece of code to force a MDX parameter on the assert tag of one test case (MDX parameter which I'm not using for anything in this particular test case):

``` xml
`   <parameter name="DaysToGoBackSQL">
        10
    </parameter>`
```

So, in conclusion, I'm defining a SQL connection string and a SQL parameter as the default for the assert tag in the settings. However, in this case, I have a test case where the assert tag will be done against a MDX connection so I changed the connection string for that particular case. For some reason, when I do this NBi will validate the parameters defined in settings for the assert tag and check that it is a SQL parameter (even if it's not used in that particular test case) and fails with the following error:

```
System.NotSupportedException : Specified method is not supported.
```

If I go the the settings to the assert tag and remove the data type of the parameter sql-type="int" the test will no longer fail, since I guess NBi now "thinks" that this is a MDX parameter (which is not what I want). The test does not fail, but this does not solve the problem.

As I've mentioned I've solved the problem by forcing a MDX parameter right in the test case, even if I'm not using it anywhere in the query.

Are you aware of this issue? Can you explain me why does this happen?

Somewhat related questions:

Am I allowed to create more than one connection string in settings per tag (e.g. assert)?
Am I allowed to create more than one parameter of different type (MDX, SQL) in settings per tag (e.g. assert)?
Are connection strings and parameters tied when defined at the settings level (for the same tag)?

I hope I've made myself clear. If you have any doubts please just ask.

**Comment by Seddryck** [comment] 2016-02-17 22:00
To be honest, I've never tried or thought to use a SQL parameter when defining a MDX query :-)

I guess the exception is directly thrown by the .Net framework and not by NBi itself. You probably can't define a type for a MDX parameter. I don't know if it's a good idea (or not) that NBi skips the type of the parameter if the query is a MDX query and not a SQL.

The key point to understand is that when you define a parameter in the settings, the parameter is not associated to a type of query (MDX or SQL).

By redefining the parameter into the test, you're overriding the definition of this parameter and so you remove the type of the parameter. NBi has no definition for the type of this overridden parameter and so has no problem to set it for a MDX query. It's the expected behaviour for an unexpected case.

Without specific knowledge of your test-suite, I'd say that you're a bit abusing the concept of defining parameters into the defaults. This concept has been introduced to cover the cases where all your SQL or MDX queries will receive parameters to limit the range of the test. By example, I've quick test-suite where I're limiting to a few days and I can easily update the value of the parameters in the settings to change it to a slow test-suite where I'm limiting to a few years. 

Could you tell me a bit more about your case: how many tests have you got? Your parameters are valid for how many tests? ... perhaps I'll be able to introduce a new feature to help you!

To answer your other questions:

> Am I allowed to create more than one connection string in settings per tag (e.g. assert)?

You can create one unique default for a given scope (system-under-test, assert, ...). If your tests require more than one connection-string for a scope, you should take a look to the [references](http://www.nbi.io/docs/config-defaults-references/#reference) but references don't accept definitions for parameters.

> Am I allowed to create more than one parameter of different type (MDX, SQL) in settings per tag (e.g. assert)?

When you define a parameter in the settings, the parameter is not associated to a type of query (MDX or SQL) ... So no you can't define two parameters with the same name and hope than one will be used for SQL and the other for MDX queries.

> Are connection strings and parameters tied when defined at the settings level (for the same tag)?

No they are not.

**Comment by bipedro** [comment] 2016-02-18 10:01
I guess I could not make myself totally clear.

You've understand most of my doubts, but I guess you've misunderstood one.

I don't think I'm abusing the concept of defining parameters into the defaults. I'm defining that the assert will always be used to connect to SQL, but, unfortunately, my test-suite will have a unique case where I need to connect to a cube ("MDX") in the assert tag. (the code sample I sent you only portrays that error, because, in fact, my test suite has 100 SQL to SQL comparison and one MDX to MDX which is the one that fails because of what I've mentioned earlier).

The problem is that, somewhat, he returns the error I've shared.

If you use the code I've sent and just change the code of the test to compare some random MDX query against the same MDX query you'll see that the test fails (the MDX connection can be exactly the same in settings - system-under-test and in the test case - assert; the SQL connection string can be any);

If you remove sql-type="int" from the settings assert parameter the tester will no longer fail (however it won't do what's needed since you need to use the parameter).

As I've told you, you have to override the parameter in the test case which is not very elegant (since you don't really need it for the query).

Maybe references, can be the solution for this particular case (but I really think this is a bug which I am not being capable of describing). I think that if you use my code you can reproduce it and you'll understand my problem better.

**Comment by FuegoArtificial** [comment] 2016-02-18 12:38
Hi bipedro,

is it clear to you that there is no connection between the connection string and parameters you define in the defaults?
If so, try to remove the connection strings in the defaults for a while and try using the parameters only. If you use the named parameters in your tests, do they work independently in MDX and SQL? If you don't type them as sql-int in the parameter definition already, you can use them as untyped strings and convert them to int in SQL or MDX queries with their respective functions itself?

Just some ideas, which may help? Maybe I misunderstand, too :)

**Comment by Seddryck** [comment] 2016-02-18 13:23
Hi @bipedro,

Based on your description, I'd say that overridding the (unneeded) parameter is not elegant but the best approach (it's I'd do personnaly). I share your point of view that due to this overriding the test is not straightforward to read and it looks a bit cumbersome to define a parameter to explain to the framework that you don't want it.

I'll let this open and try to find an alternative to express that you don't want to inherit from a parameter. My goal will be to improve the readability of the test. What do you think about :+1: 

``` xml
       <assert>
            <equalTo> <column  index="0" role="value" type="numeric"  />
                <query connectionString="mdx connection string">
                    mdx code
                    <parameter name="DaysToGoBackSQL" action="remove">
                </query>
            </equalTo>
        </assert>
```

or something as

``` xml
       <assert>
            <equalTo> <column  index="0" role="value" type="numeric"  />
                <query connectionString="mdx connection string" inherits-parameters="false">
                    mdx code
                </query>
            </equalTo>
        </assert>
```

Comments and suggestions for other syntax are welcome.

**Comment by bipedro** [comment] 2016-02-19 11:51
Hi,

@Seddryck, both approaches would work well. I personally don't have any suggestions, but I'm all in favor of readability (documentation would be paramount I guess). By the way, let me congratulate you and your team for the documentation provided which is very easy to follow and self-explanatory.

@FuegoArtificial, in truth I cannot really grasp the problem. Are you able to provide a easy explanation of why a parameter that I'm not using in a test is giving me problems?

Thanks for your suggestions. I could pass the parameter as a TEXT (string), but I guess that handling it in the SQL query would not be a very performance oriented option. However, in my particular case, this just happens for one of my tests, which is not a big problem for now. As I add more tests to the test suite this might become a problem.

I might try to use references to define global connection strings, but this would not be optimal. I guess I will maintain my "bogus" parameter for now as defined in the test case. If this becomes a real issue I'll take a look a it in the future.

Thanks for all your help.

**Comment by Seddryck** [comment] 2016-02-19 14:04
@bipedro , @FuegoArtificial I've not been clear about why you had the problem. In fact all parameters defined (in the test or in the settings) are **always** transferred to the server: NBi doesn't parse your query to know if the parameter is needed or is not expected. It's usually not problem because a SQL server doesn't care about receiving pointless parameter but in your specific case, NBi tries to submit a SQL parameter to an MDX server.

I think that removing the sql-type of your definition in the settings shouldn't create too many issues but it would be interesting to confirm.

**Comment by Seddryck** [comment] 2016-02-29 21:43
Preview available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.13.0-ci.35

Supports:

``` xml
 <assert>
            <equalTo> <column  index="0" role="value" type="numeric"  />
                <query connectionString="mdx connection string">
                    mdx code
                    <parameter name="DaysToGoBackSQL" remove="true">
                </query>
            </equalTo>
        </assert>
```

**Closed as completed** 2016-04-16 10:39 UTC
Labels: feature-request, preview-available
