### ISSUE TITLE
Support for Data Source using asazure protocol

### ISSUE THREAD

**Issue by Tannenwedel** [Seddryck/NBi#394] opened 2018-07-18 01:33 UTC
Hi @Seddryck,

does NBi support connection strings with data sources that use the asazure protocol like this?

```xml
<query connectionString="Provider=MSOLAP;Data Source=asazure://westeurope.asazure.windows.net/mydb;Initial Catalog=myCatalog;">
```

 Currently it fails to parse the connection string (is appears to be looking for a port, that is not required): 
```
 NBi.NUnit.Runtime.TestSuite.My Test:
System.AggregateException : One or more errors occurred.
  ----> NBi.Core.ConnectionException : The connection string is not valid.
The connection string used was 'Provider=MSOLAP;Data Source=asazure://westeurope.asazure.windows.net/mydb;Initial Catalog=myCatalog;'
  ----> System.FormatException : Input string was not in a correct format.
```
  
 Stacktrace:
 ```
--FormatException
at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
at Microsoft.AnalysisServices.AdomdClient.XmlaClient.GetInstancePort(ConnectionInfo connectionInfo)
```

--- Edit:

It seems that connecting to Azure Analysis Services requires Microsoft.AnalysisServices.AdomdClient.dll in version 14.0.800.117 or later whereas NBi uses version 12.0.0.0. Are there any plans to update this?

Thanks

**Comment by Seddryck** [comment] 2018-07-18 06:30
I never tested this, can’t confirm. I’ll check in documentation of ASA and if needed upgrade to the last version of adomd. Should be part of the next release.

**Comment by Seddryck** [comment] 2018-07-19 08:38
I just compiled a new version of NBi with the new Adomd package at https://ci.appveyor.com/project/Seddryck/nbi/build/1.18.0-alpha.1+165.build.429/artifacts

@Tannenwedel: could you confirm that it effectively fix your issues with asazure ?

**Comment by Tannenwedel** [comment] 2018-07-23 00:41
Hi,
the connection to the Azure Analysis Services can be established now. 

Thanks!

**Comment by Seddryck** [comment] 2018-07-23 09:21
Ok, thx for the feedback and the tip about the root cause. Merged to develop branch and available in beta at https://ci.appveyor.com/project/Seddryck/nbi/build/1.19.0-beta.42.build.433/artifacts  or ```Update-Package NBi.Framework -Version 1.19.0-beta0042```

**Closed as completed by Seddryck** 2018-07-23 09:21 UTC
Labels: feature-request, beta-available
