### ISSUE TITLE
.dll's lost when building the solution

### ISSUE THREAD

**Issue by MarcoCh** [Seddryck/NBi#99] opened 2015-07-29 04:03 UTC
I downloaded the source code and when I try to build the solution it throws several errors and warnings saying that the .dll's (NBi.Core.dll, NBi.Xml.dll, NBi.Testing.dll,...) are lost. Where can I find those .dll's?

**Comment by Seddryck** [comment] 2015-07-29 08:15
These dlls with a name starting by nbi.\* are part of this solution. Other external references are from nuget except a few from Microsoft sql server. Building the solution with VS 2013 should make the job. I doubt the root cause is linked to the nbi.\* dlls. The probabilities are higher for sql server related dlls. Have you got sql server 2014 on your build platform?

Have you downloaded (from where) or forked the sources (which branch)?

**Comment by MarcoCh** [comment] 2015-07-29 20:25
I'm using VS 2012 and SQL Server 2012 also I downloaded the branch for the release v1.10. I already fix the issue that I was having (the build order).

I was going to ask you, I need to do testing on a Teradata database and I notice (from the source code) that is no supported in this version, which changes (and where) do I have to make in order to allow a Teradata connection? 

I would appreciate a full and soon response

**Comment by Seddryck** [comment] 2015-07-30 10:26
Hello,

Would be easier, if you separate the two issues (build issue and teradata connection) by creating a new issue. 

It would be easier to guide you, if you share your code with a fork. Btw, I'm on holidays at the moment (with limited resources to help you) but I will be back at home this weekend. 

I have some doubts about the build order issue that you describe but more likely you have issues to compile Nbi.core because of the lack of ssis 2014 installed on your machine. Switch the corresponding references to version 11.0 (2012) and it will be ok. 

The easy way: To add a new type of db engine, from the top of my head, everything should be done in Nbi.core. The first point to investigate is the class connectionFactory then depending of the connection string used (oledb or native) you could also need to create a queryteradataengine and add it to to the queryenginefactory. Personally I'd go for an oledb connection, it's probably less work. (Don't forget that the provider should be installed on your dev machine).

The hard way: do the same in a new dll and add a system to look into other dlls, to find the new class and register them in the corresponding factories (part of 2.0).

**Comment by Seddryck** [comment] 2015-08-01 22:25
Please, fill free to post additional comments to #101 and #102 about Teradata connection and keep this issue for build order.

I've re-checked the build order and found no mistake. Could you explain what you've updated?

**Comment by MarcoCh** [comment] 2015-08-02 03:56
About the build order probably by mistake I changed it. When I upgraded VS and SQL Server to VS 2013 and SQL Server 2014 it built  successfully this time.

**Comment by Seddryck** [comment] 2015-08-02 12:13
Ok, thx for your feedback. If there is no problem with the build order, I'll close this issue.

**Closed as completed by Seddryck** 2015-08-02 12:13 UTC
