### ISSUE TITLE
30 seconds timeout in queries set as standard

### ISSUE THREAD

**Issue by FuegoArtificial** [Seddryck/NBi#267] opened 2017-03-29 11:54 UTC
Hello,

in version 1.14.0.1 I sometimes have the issue that a query runs into a timeout of 30 seconds although I'm not aware that I defined this threshold.
Is this known and does someone know how to workaround this constraint?
I didn't observe it in all versions so I'm confused how to tackle this.

Cheers

**Comment by Seddryck** [comment] 2017-03-29 20:15
Check #254 #221 and #54 ;-)

**Comment by FuegoArtificial** [comment] 2017-03-30 07:54
Thank you! 
Do I understand correctly that 30 seconds is the standard and it has to be overridden by the timeout-milliSeconds-property if I need a different or no timeout? If so then I know I'll have to adjust the templates to use current nbi-versions and it's fine. 
I just want to make sure that I don't do anything wrong :)
Thanks again!

**Comment by Seddryck** [comment] 2017-03-30 08:57
Something clear is that the attribute ```timeout-milliSeconds``` will help you to override the default timeout.

Something less clear is the default timeout. Documentation says that the default timeout is "no timeout". From the top of my head it was also the design (no descrepency between doc/design). But you experience is that the default timeout is 30 seconds (FYI, 30 seconds is the default value for any IDbCommand in .NET). 

I see following potential root causes:

* Not last version of NBi
* Specifically related to your test (you're using the ```query``` at a place where the default time-out is not implemented)

But I need your help to remove one or two of these options :-)

**Comment by FuegoArtificial** [comment] 2017-03-30 11:44
Hi Seddryck,

we tried to figure some things. Let's see if it helps to find the next step to tackle this?
- one query connects to PDW (APS), another one to a SQL Server 2008 R2 SP1, which both fail with the timeout
- using 1.11.0.14 works for both queries which last longer than 30 seconds with the same template
- using 1.14.0.1, 1.14.0.7 and build 1.15.0.58 run into the timeout

Can I provide more detailed information which may help? Perhaps the template, the xml of the test-instance or something alike? Testing with other versions to narrow down where there might have occured a change?

Cheers :)

**Comment by Seddryck** [comment] 2017-03-30 11:57
Hi Tilo,

Could you put a copy of your test, I just want to check the pattern (Is it an Excution/Query/EqualTo test or something more advanced?). Then I'll add a few tests to the test-suite to see where it suddenly fail.

I also need to know if it's a SQLCLI provider; an OleDB or an ODBC connection string :-)

Could you also confirm that the usage of the timeout-milliSeconds attribute overrides the default timeout?

Thx.

**Comment by Seddryck** [comment] 2017-03-30 14:12
Personnal comments: 

testing with ```WAITFOR DELAY '00:00:45'``` and a SqlClient connection string (no provider defined)

* v1.15-CI
    * execution: failed
    * equalTo: failed
* v1.14 - 2017-01-27
    * execution: failed
    * equalTo: failed
* v1.13 - 2016-08-10
    * execution: OK
    * equalTo: failed
* v1.12 - 2015-12-14
    * execution: OK
    * equalTo: OK
* v1.11
    * execution: OK
    * equalTo: OK

**Comment by Seddryck** [comment] 2017-03-30 15:11
Before release 1.13, the timeout was always enforced to "no timeout" just before the execution of the query. This release introduced the option to define a timeout with #160

**Comment by Seddryck** [comment] 2017-03-30 15:15
#160 introduced the timeout only at the ```execution``` level. It explains why it was a different result for ```equalTo```

**Comment by Seddryck** [comment] 2017-03-30 15:19
With #208 (part of 1.14) the notion of timeout was extended to ```equalTo``` ... it is probably there that I unfortunately changed something to the default value of the timeout.

**Comment by Seddryck** [comment] 2017-03-30 15:34
Found the root cause: 

* If no value is defined in the Xml the timeout is set to 0 (ok)
* in CommandBuilder, the line to set the timeout to the value defined in the test is surrounded by a check that this timeout is greater than 0. Because of this check, no value is provided to the command and the default value of the .net framework (30 seconds) is used. 

That's an easy fix and I'll apply it tonight. (Can read code from my iPhone but not write code).

**Comment by FuegoArtificial** [comment] 2017-03-30 15:39
Wow, that's true dedication to your work!
I was about to ask if I can still support here, but then the message popped up that you already found the issue. That's nice to hear! :)

**Comment by Seddryck** [comment] 2017-03-30 18:06
To go back to home, I've to sit down in a train during 35 minutes. It was more than enough to check where I could have introduced this bug :-)

Should be fixed in https://ci.appveyor.com/project/Seddryck/nbi/build/1.15.0-ci.63 : if no timeout is defined in the xml the default timeout is "no timeout".

If ok for you could you close this issue? Thx.

**Comment by FuegoArtificial** [comment] 2017-03-31 11:11
Hi Cedric,

thanks for the quick fix! 

We have tested the build and ran into issues.
- The fix worked for the specific cases.
- When generating the entire test suite we ran into a timeout of genbi. We are investigating, at which point the issue pops up and if it's a non-nbi-issue (like write protected previous test suite-file etc...)

I'll get back as soon as we know more.

**Comment by Seddryck** [comment] 2017-03-31 11:51
If this bug is fixed, I'll close the issue. Feel free to open a new one if the genbi has issues.

**Closed as completed by Seddryck** 2017-03-31 11:51 UTC
Labels: bug, preview-available

**Comment by Seddryck** [comment] 2017-08-24 21:15
Available in beta: https://github.com/Seddryck/NBi/releases/tag/v1.15-beta
