### ISSUE TITLE
If the test fails then the tasks in the cleanup element are not executed

### ISSUE THREAD

**Issue by WimDeRons** [Seddryck/NBi#142] opened 2015-11-19 06:57 UTC
I'm using a sql script in the cleanup tag (to drop an auxilary table created by a sql script in the setup tag). But the script is not executed. Code example:

```
<cleanup>
<sql-run name="ScriptName.sql" path="..\FolderName\SQL\"/>
</cleanup>
```

Extra info:
- I'm using a default connection string for setup-cleanup (also tested using an explicit connectionString in the sql-run tag, in this case I used a referenced connection string)
- When the sql-run tag from cleanup is copied into setup, it does run the sql script when executing the test (to verify there are no mistakes in the file and folder name)
- Tested on versions 1.10.0.19 and 1.12.0.1

**Comment by Seddryck** [comment] 2015-11-27 11:54
Wim, I can't reproduce and I'm sure that nothing has changed on this topic since 1.12-beta. We should check together.

**Comment by WimDeRons** [comment] 2015-12-03 13:24
Cédric, after reducing my test to a bare minimum, it seems to be related to the outcome of the test itself:
- when the test passes, the cleanup is executed
- when the test fails, the cleanup is not executed

**Comment by Seddryck** [comment] 2015-12-23 13:28
Wim, should be fixed but difficult for me to confim: https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.12.0.99088

**Closed as completed by Seddryck** 2015-12-23 13:28 UTC
Labels: bug, preview-available

**Comment by WimDeRons** [comment] 2015-12-24 12:57
Cédric, on my side I can confirm that when using build 1.12.0.99088, the cleanup is executed in both scenarios. Thanks!
